### ISSUE TITLE
RAISR输出结果不对

### ISSUE THREAD

**Issue by excllent123** [YHJRUBY/RAISR#1]
Hi  YHJRUBY:
     请问训练好的 filter是几倍分辨率下？目前测试的filter 在三倍放大下  结果不对。

Best regards

**Comment by ye-hongjiang** [comment]
@excllent123 训练好的是三倍的。刚刚更新了一些代码，可以再试试

**Comment by excllent123** [comment]
@YHJRUBY   请问训练用了多少图？我用200幅图像2X放大情况下，效果不好。

**Comment by ye-hongjiang** [comment]
@excllent123 320张。效果不好可能是和论文实现有区别，例如对训练图片的翻转变换并不能都改变 hash 值。可以看看模型有没有什么问题。
